// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: greeter.proto

package go_micro_srv_greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.WS
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GretterService service

type GretterService interface {
	Say(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type gretterService struct {
	c    client.Client
	name string
}

func NewGretterService(name string, c client.Client) GretterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.greeter"
	}
	return &gretterService{
		c:    c,
		name: name,
	}
}

func (c *gretterService) Say(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GretterService.Say", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GretterService service

type GretterServiceHandler interface {
	Say(context.Context, *Request, *Response) error
}

func RegisterGretterServiceHandler(s server.Server, hdlr GretterServiceHandler, opts ...server.HandlerOption) error {
	type gretterService interface {
		Say(ctx context.Context, in *Request, out *Response) error
	}
	type GretterService struct {
		gretterService
	}
	h := &gretterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GretterService{h}, opts...))
}

type gretterServiceHandler struct {
	GretterServiceHandler
}

func (h *gretterServiceHandler) Say(ctx context.Context, in *Request, out *Response) error {
	return h.GretterServiceHandler.Say(ctx, in, out)
}
